CREATE TABLE uk_local_authorities (
  "Register" VARCHAR(19) NOT NULL,
  "local-authority-code" VARCHAR(5) NOT NULL,
  "register-and-code" VARCHAR(25) NOT NULL,
  "local-authority-type" VARCHAR(3),
  "local-authority-type-name" VARCHAR(28),
  "overlapping-la" VARCHAR(3),
  "official-name" VARCHAR(52) NOT NULL,
  "alt-name-1" VARCHAR(36) NOT NULL,
  "alt-name-2" VARCHAR(29),
  "alt-name-3" VARCHAR(27),
  "gov-uk-slug" VARCHAR(28),
  "start-date" VARCHAR(8),
  "end-date" VARCHAR(8),
  "gss-code" VARCHAR(9),
  "archaic-gss-code" VARCHAR(10),
  "old-ons-la-code" VARCHAR(4),
  ofcom VARCHAR(9),
  snac VARCHAR(4),
  os DECIMAL,
  ecode VARCHAR(5),
  notes VARCHAR(106)
);

COPY uk_local_authorities("Register",
                          "local-authority-code",
                          "register-and-code",
                          "local-authority-type",
                          "local-authority-type-name",
                          "overlapping-la",
                          "official-name",
                          "alt-name-1",
                          "alt-name-2",
                          "alt-name-3",
                          "gov-uk-slug",
                          "start-date",
                          "end-date",
                          "gss-code",
                          "archaic-gss-code",
                          "old-ons-la-code",
                          "ofcom",
                          "snac",
                          "os",
                          "ecode",
                          "notes")
FROM '/Users/endamccormack/GDS/open-geo-spatial-api/external-data/uk_local_authority_names_and_codes/uk_local_authorities.utf8.csv' DELIMITER ',' CSV HEADER;
